# Generated by Django 4.1.4 on 2022-12-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('fullname', models.CharField(default='', max_length=70)),
                ('name', models.CharField(max_length=62)),
                ('description', models.CharField(max_length=277, null=True)),
                ('gh_readme', models.TextField(null=True)),
                ('author', models.CharField(max_length=24)),
                ('stargazers_count', models.IntegerField()),
                ('watchers_count', models.IntegerField()),
                ('forks_count', models.IntegerField()),
            ],
        ),
    ]
