# Generated by Django 4.1.4 on 2022-12-29 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
    ]
