# Generated by Django 3.2.16 on 2023-01-03 04:29
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_auto_20230104_0337'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
              ALTER TABLE package_package DROP COLUMN IF EXISTS vector_column;
              ALTER TABLE package_package ADD COLUMN vector_column tsvector GENERATED ALWAYS AS (
                setweight(to_tsvector('english', coalesce(gh_readme, '')), 'A') ||
                setweight(to_tsvector('english', coalesce(author, '')), 'B') ||
                setweight(to_tsvector('english', coalesce(description, '')), 'C') ||
                setweight(to_tsvector('english', coalesce(fullname, '')), 'D')
              ) STORED;
              CREATE INDEX package_pac_vector__90fbfb_gin ON package_package USING gin(vector_column);
            ''',

            reverse_sql = ''''''
        ),
    ]
