# Generated by Django 3.2.16 on 2023-01-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_create_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='topics',
            field=models.CharField(default='[]', max_length=317),
        ),
    ]
