# Generated by Django 3.2.16 on 2023-01-02 15:32
import os
from django.db import connection
from django.db import migrations


def load_data_from_sql(apps, schema_editor):
   file_path = os.path.join(os.path.dirname(__file__), 'fill_database.sql')
   sql_statement = open(file_path).read()
   with connection.cursor() as c:
       c.execute(sql_statement)
       
def remove_data_from_sql(apps, schema_editor):
    with connection.cursor() as c:
       c.execute('truncate package_package cascade;')

class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_package_topics'),
    ]

    operations = [
        migrations.RunPython(code=load_data_from_sql, reverse_code=remove_data_from_sql)
    ]
